---
abstract: 'Locking via Redis'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-ConcurrencyLimit-Lock-Redis
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Class::XSAccessor: 1.12
  Data::UUID::MT: 0
  File::Spec: 0
  IPC::ConcurrencyLimit: 0.10
  IPC::ConcurrencyLimit::Lock: 0
  Redis: 1.955
  Redis::ScriptCache: 0.01
version: 0.01
